GET http://localhost:3001/api/contacts

###
GET http://localhost:3001/api/contacts/5

###
DELETE http://localhost:3001/api/contacts/1

###
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
    "name": "Alec German",
    "number": "123-456-7890"
}