GET http://localhost:3001/api/contacts

###
GET http://localhost:3001/api/contacts/67413b0f97b473f1ce1c6bf3

###
DELETE http://localhost:3001/api/contacts/67413b0f97b473f1ce1c6bf3

###
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
    "name": "Leon Kennedy",
    "number": "777-777-7777"
}

###
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
    "name": "James Sunderland",
    "number": "333-333-3333"
}